services:
  web:
    build: ..
    volumes:
      - sock:/var/run/lighttpd
  socat:
    image: alpine
    command: sh -c 'apk add --no-cache -q socat && exec socat TCP-LISTEN:3000,fork,reuseaddr UNIX-CONNECT:/var/run/lighttpd/sock'
    ports:
      - "3000:3000"
    volumes:
      - sock:/var/run/lighttpd
    depends_on:
      - web
volumes:
  sock:
